text: &text Source Code Pro:style=Medium:size=18
icon: &icon Overpass Nerd Font:style=Solid:size=18

active_line: &active_line
  foreground: F9F9F9FF
inactive_line: &inactive_line
  foreground: B3C4E0FF
red_line: &red_line
  margin: 10
  foreground: FF247CFF
separator_line: &separator_line
  foreground: 211C2EFF
  text: " ▎"
  margin: 7

bar:
  height: 38
  location: top
  margin: 0
  font: *text 
  foreground: B3C4E0FF
  background: 171322FF
  border:
    bottom-width: 2
    color: 211C2EFF
  left:
    - label:
        content:
          string: {<<: *separator_line}
    - i3:
        sort: ascending
        strip-workspace-numbers: true
        spacing: 0
        anchors:
          - string: &default {text: " {name}", font: *icon}
        content:
          "":
            map:
              conditions:
                state == focused:
                  - string: {<<: [*default, *active_line]}
                  - string: {<<: *separator_line}
                state == unfocused:
                  - string: {<<: [*default, *inactive_line]}
                  - string: {<<: *separator_line}
                state == invisible: 
                  - string: {<<: *default}
                  - string: {<<: *separator_line}
          current:
            map:
              conditions:
                mode == "default":
                  - {empty: {}}
                mode == "resize":
                  - string: {<<: *active_line, text: ' 󰩨 ' }
                  - string: {<<: *separator_line}
                mode == "capture":
                  - string: {<<: *active_line, text: ' 󰻃' , font: *icon}
                  - string: {<<: *separator_line}
                mode == "music":
                  - string: {<<: *active_line, text: ' 󰗅' , font: *icon}
                  - string: {<<: *separator_line}
                mode == "power":
                  - string: {<<: *red_line, text: ' 󰗼' , font: *icon, on-click: "swaymsg exit"}
                  - string: {<<: *red_line, text: '' , font: *icon, on-click: "loginctl reboot"}
                  - string: {<<: *red_line, text: '' , font: *icon, on-click: "loginctl poweroff"}
                  - string: {<<: *separator_line}
    - mpd:
        host: localhost
        port: 6600
        content:
          list:
            spacing: 2
            items:
              - string: {<<: *inactive_line, text: "{title} {pos}/{end}", left-margin: 5, max: 60}
              - string: {<<: *inactive_line, text: '󰝚' ,font: *icon}
    - label:
        content:
          string: {<<: *separator_line}
  right:
    - label:
        content:
          string: {<<: *separator_line}
    - pipewire:
        anchors:
          volume: &volume
              conditions:
                muted:
                  - string: {text: "{cubic_volume}%"}
                ~muted: 
                  - string: {text: "{cubic_volume}%"}
        content:
          list:
            spacing: 5
            items:
              - map:
                  on-click: "foot -a mixer pulsemixer"
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          muted:
                            - string: {<<: *inactive_line, text: '󰝟' ,font: *icon}
                          ~muted: 
                            list:
                              spacing: 2
                              items:
                                - string: {<<: *inactive_line, text: "{cubic_volume}%"}
                                - ramp:
                                    tag: cubic_volume
                                    items:
                                      - string: {<<: *inactive_line, text: '' ,font: *icon}
                                      - string: {<<: *inactive_line, text: '' ,font: *icon}
                                      - string: {<<: *inactive_line, text: '󰕾' ,font: *icon}
                                      - string: {<<: *inactive_line, text: '' ,font: *icon}
                    type == "source":
                      map:
                        conditions:
                          muted:
                            - string: {<<: *separator_line}
                            - string: {<<: *inactive_line, text: '' ,font: *icon}
                          ~muted:
                            list:
                              spacing: 2
                              items:
                                - string: {<<: *separator_line}
                                - string: {<<: *inactive_line, text: "{cubic_volume}%"}
                                - string: {<<: *inactive_line, text: '' ,font: *icon}
                            
    - network:
        name: wlp3s0
        poll-interval: 1000
        content:
          map:
            default:
              - string: {<<: *separator_line}
              - string: {text: '󰤮', font: *icon}
            conditions:
              state == down:
                - string: {<<: *separator_line}
                - string: {text: '󰤫', font: *icon}
              state == up:
                list:
                  spacing: 2
                  items:
                    - string: {<<: *separator_line}
                    - string: {<<: *inactive_line, text: "{ssid}"}
                    - ramp:
                        tag: signal
                        min: -90
                        max: -30
                        items:
                          - string: {<<: *inactive_line, text: '󰤯', font: *icon}
                          - string: {<<: *inactive_line, text: '󰤟', font: *icon}
                          - string: {<<: *inactive_line, text: '󰤢', font: *icon}
                          - string: {<<: *inactive_line, text: '󰤥', font: *icon}
                          - string: {<<: *inactive_line, text: '󰤨', font: *icon}
    - cpu:
        content:
          map:
            conditions:
              id < 0:
                list:
                  spacing: 3
                  items:
                    - string: {<<: *separator_line}
                    - string: {<<: *inactive_line, text: "{cpu}%"}
                    - string: {<<: *inactive_line, text: '' , font: *icon}
    - mem:
        content:
          list:
            spacing: 3
            items:
              - string: {<<: *separator_line}
              - string: {<<: *inactive_line, text: "{used:mb}MB"}
              - string: {<<: *inactive_line, text: '' ,font: *icon}
    - backlight:
        name: amdgpu_bl0
        content:
          list:
            spacing: 3
            items:
              - string: {<<: *separator_line}
              - string: {<<: *inactive_line, text: "{percent}%"}
              - ramp:
                  tag: brightness
                  items:
                    - string: {<<: *inactive_line, text: '󱩏', font: *icon}
                    - string: {<<: *inactive_line, text: '󱩐', font: *icon}
                    - string: {<<: *inactive_line, text: '󱩓', font: *icon}
                    - string: {<<: *inactive_line, text: '󱩔', font: *icon}
                    - string: {<<: *inactive_line, text: '󱩕', font: *icon}
                    - string: {<<: *inactive_line, text: '󱩖', font: *icon}
                    - string: {<<: *inactive_line, text: '󰛨', font: *icon}
    - battery:
        name: BAT0
        poll-interval: 500
        anchors:
          discharging: &discharging
            list:
              spacing: 3
              items:
                - string: {<<: *separator_line}
                - string: {<<: *inactive_line, text: "{capacity}%"}
                - ramp:
                    tag: capacity
                    items:
                      - string: {<<: *inactive_line, text: '󰁺', font: *icon}
                      - string: {<<: *inactive_line, text: '󰁻', font: *icon}
                      - string: {<<: *inactive_line, text: '󰁼', font: *icon}
                      - string: {<<: *inactive_line, text: '󰁽', font: *icon}
                      - string: {<<: *inactive_line, text: '󰁾', font: *icon}
                      - string: {<<: *inactive_line, text: '󰁿', font: *icon}
                      - string: {<<: *inactive_line, text: '󰂀', font: *icon}
                      - string: {<<: *inactive_line, text: '󰂁', font: *icon}
                      - string: {<<: *inactive_line, text: '󰁹', font: *icon}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                list:
                  spacing: 3
                  items:
                    - string: {<<: *separator_line}
                    - string: {<<: *inactive_line, text: "{capacity}%"}
                    - string: {<<: *inactive_line, text: '󰂄', font: *icon}
              state == full:
                list:
                  spacing: 3
                  items:
                    - string: {<<: *separator_line}
                    - string: {<<: *inactive_line, text: "{capacity}%"}
                    - string: {<<: *inactive_line, text: '󱟢', font: *icon}
              state == "not charging":
                <<: *discharging
    - clock:
        time-format: "%H:%M"
        content:
          list:
            spacing: 3
            items:
              - string: {<<: *separator_line}
              - string: {<<: *inactive_line, text: "{time}"}
              - string: {<<: *inactive_line, text: '', font: *icon}
              - string: {<<: *separator_line}
              - string: {<<: *inactive_line, text: "{date}"}
              - string: {<<: *inactive_line, text: '', font: *icon}
    - label:
        content:
          - string: {text: "▎", margin: 10, foreground: 211C2EFF }
